-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- local group_prefix = "bestform_"
--
-- vim.api.nvim_create_autocmd({ "InsertLeave", "TextChanged" }, {
--   group = vim.api.nvim_create_augroup(group_prefix .. "auto-save", { clear = true }),
--   callback = function(ev)
--     -- acwrite is the filetype of the oil buffer
--     if vim.bo[ev.buf].buftype ~= "nofile" and vim.bo[ev.buf].buftype ~= "acwrite" then
--       vim.cmd("!silent write")
--       print("saved")
--     end
--     return true
--   end,
-- })
